### PR TITLE
Modification to Web USB App more in line with current ProffieOS capabilities

### PR DESCRIPTION
**Pull request by artandtechvof**
Main menu;

Added buttons for stab, melt and lightning block

Added slider and input field for variation (lets fine tune your color, and also lest you reset a preset that has its variation set to non-zero)

Added different style for volume slider, making it easier to use on smaller mobile devices

Fixed highlighting of playing track

Edit menu;

After edit field has modified an item, send Setpreset(current_preset_num) to reselect current preset and let it take immediate effect.

Drag and drop delete does not work on chrome on windows PC, Click on delete preset button now also deletes preset.

Duplicating and deleting a preset has to be confirmed first via alert message.

Made addon folder selection option for sound fonts, for common menu sounds etc.

changed myselect style to center items if highlighted textbox

Changed order of menu items

Todo;
Serial direct (via Node.js server-serial-bridge for Teensy without WebUSB and/or Ble capabilities)

If you want you can try out this version on our github.io page

https://artandtechvof.github.io/app.html

### CODE REVIEW

**Comment by profezzorn** [comment]
This is a lot of changes in one CL, most of which looks really good, but it's a lot easier to review and understand one change at a time whenever possible.  Would it be ok with you to split this up into a series of smaller changes?

**Comment by artandtechvof** [comment]
No problem, I will do it to the best of my knowledge.

If you allow me, I would also like to make a youtube tutorial on the usage of the Web-app, as an 'entry-level' ProffieOS configurator. 
Many of our customers (and a lot of Proffie-users) are non-programmers, but would be able to customize their saber using the web-app without any programming knowledge at all, and no need to install Arduino, Teensyduino, zadig etc.
For more advanced styles, the style-editor and configfile + Arduino upload would be the next step.

**Comment by profezzorn** [comment]
Thank you for splitting up the review. It makes it much easier! and it means that non-controversial pieces can be merged immediately :) The WebUSB editor was always meant to be used as an "entry level" editor, so I'm happy to see it potentially used that way.  You don't need permission to make a youtube tutorail, and if you did, you would surely have it.... :)

**Comment by artandtechvof** [comment]
Thank your for your consent in making a tutorial and spreading the word!
We build sabers (and other props) for our customers, and they are encouraged to help design and build there own saber wherever they feel they want to participate. Its more an extended 'lightsaber-workshop/course', By the time we get to programming the saber, the WebAPP is often invaluable to get the basic understanding how to modify your own saber. So if not for the community, than at least for our customers it would help a lot to have a youtube tutorial, like fetf263 has done so brilliantly for the style editor.

**Pull request closed without merging**
